RAW_DATA = "./data_derived/"
DERIVED_DATA = "./data_derived/"
CHECKPOINTS = "/mnt/d/Documents/dorsalnet/pretrained/"
CPC_DPC = "./Documents/ventral-dorsal-model/Models/CPC/dpc"
CPC_BACKBONE = "./Documents/ventral-dorsal-model/Models/CPC/backbone"
